"""0001 baseline existing schema

Revision ID: 27eba23abfeb
Revises: 
Create Date: 2026-05-24 07:58:42.940987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector  # pgvector-Typ fuer workshop_entity_embeddings.embedding

# revision identifiers, used by Alembic.
revision: str = '27eba23abfeb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector-Extension sicherstellen (fuer workshop_entity_embeddings.embedding).
    # Idempotent — auf der Live-DB bereits vorhanden, auf frischen DBs neu angelegt.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('workshop_access_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('path_template', sa.String(length=255), nullable=True),
    sa.Column('query_string', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('ua_short', sa.String(length=80), nullable=True),
    sa.Column('referer_path', sa.String(length=255), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_duration_ms', sa.Integer(), nullable=True),
    sa.Column('llm_call_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_log_model_time', 'workshop_access_log', ['llm_model', 'created_at'], unique=False)
    op.create_index('ix_access_log_path_time', 'workshop_access_log', ['path_template', 'created_at'], unique=False)
    op.create_index('ix_access_log_user_time', 'workshop_access_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workshop_access_log_created_at'), 'workshop_access_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_workshop_access_log_llm_model'), 'workshop_access_log', ['llm_model'], unique=False)
    op.create_index(op.f('ix_workshop_access_log_path'), 'workshop_access_log', ['path'], unique=False)
    op.create_index(op.f('ix_workshop_access_log_path_template'), 'workshop_access_log', ['path_template'], unique=False)
    op.create_index(op.f('ix_workshop_access_log_status_code'), 'workshop_access_log', ['status_code'], unique=False)
    op.create_index(op.f('ix_workshop_access_log_user_id'), 'workshop_access_log', ['user_id'], unique=False)
    op.create_table('workshop_agenda_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.Enum('VORTRAG', 'DISKUSSION', 'WORKSHOP', 'PAUSE', 'ORGANISATION', name='agendaitemtype'), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), server_default=sa.text("'plenary'"), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DONE', 'SKIPPED', name='agendaitemstatus'), server_default=sa.text("'PENDING'::agendaitemstatus"), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('related_thread_ids', sa.JSON(), nullable=True),
    sa.Column('related_file_ids', sa.JSON(), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_audit_report_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('auftraggeber', sa.String(length=120), nullable=True),
    sa.Column('pruefer_name', sa.String(length=120), nullable=True),
    sa.Column('pruefer_user_id', sa.String(length=36), nullable=True),
    sa.Column('state_aid_hits', sa.Integer(), nullable=True),
    sa.Column('beneficiaries_hits', sa.Integer(), nullable=True),
    sa.Column('sanctions_hits', sa.Integer(), nullable=True),
    sa.Column('cross_references', sa.Integer(), nullable=True),
    sa.Column('pdf_size_bytes', sa.Integer(), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_report_query_created', 'workshop_audit_report_log', ['query', 'created_at'], unique=False)
    op.create_index(op.f('ix_workshop_audit_report_log_created_at'), 'workshop_audit_report_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_workshop_audit_report_log_pruefer_user_id'), 'workshop_audit_report_log', ['pruefer_user_id'], unique=False)
    op.create_index(op.f('ix_workshop_audit_report_log_query'), 'workshop_audit_report_log', ['query'], unique=False)
    op.create_table('workshop_beneficiary_harvest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('records_seen', sa.Integer(), server_default='0', nullable=True),
    sa.Column('records_inserted', sa.Integer(), server_default='0', nullable=True),
    sa.Column('records_skipped', sa.Integer(), server_default='0', nullable=True),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=80), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_beneficiary_harvest_runs_source_key'), 'workshop_beneficiary_harvest_runs', ['source_key'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_harvest_runs_started_at'), 'workshop_beneficiary_harvest_runs', ['started_at'], unique=False)
    op.create_table('workshop_beneficiary_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_key', sa.String(length=120), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('upload_run_id', sa.String(length=36), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_sheet', sa.String(length=80), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('beneficiary_name', sa.Text(), nullable=False),
    sa.Column('beneficiary_name_normalized', sa.Text(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_aktenzeichen', sa.String(length=120), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('bundesland', sa.String(length=80), nullable=True),
    sa.Column('fonds', sa.String(length=40), nullable=True),
    sa.Column('periode', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('landkreis', sa.String(length=120), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('nuts_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cost_total_raw', sa.String(length=80), nullable=True),
    sa.Column('cost_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_eu_funding_raw', sa.String(length=80), nullable=True),
    sa.Column('cost_eu_funding', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('project_start_raw', sa.String(length=40), nullable=True),
    sa.Column('project_start', sa.Date(), nullable=True),
    sa.Column('project_end_raw', sa.String(length=40), nullable=True),
    sa.Column('project_end', sa.Date(), nullable=True),
    sa.Column('funded_at_raw', sa.String(length=40), nullable=True),
    sa.Column('funded_at', sa.Date(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'source_record_id', name='uq_beneficiary_source_record')
    )
    op.create_index('ix_beneficiary_country_bundesland', 'workshop_beneficiary_records', ['country_code', 'bundesland'], unique=False)
    op.create_index('ix_beneficiary_search', 'workshop_beneficiary_records', ['beneficiary_name_normalized'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_beneficiary_name_normalized'), 'workshop_beneficiary_records', ['beneficiary_name_normalized'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_bundesland'), 'workshop_beneficiary_records', ['bundesland'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_cost_total'), 'workshop_beneficiary_records', ['cost_total'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_country_code'), 'workshop_beneficiary_records', ['country_code'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_fonds'), 'workshop_beneficiary_records', ['fonds'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_funded_at'), 'workshop_beneficiary_records', ['funded_at'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_nuts_code'), 'workshop_beneficiary_records', ['nuts_code'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_source_key'), 'workshop_beneficiary_records', ['source_key'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_source_record_id'), 'workshop_beneficiary_records', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_workshop_beneficiary_records_upload_run_id'), 'workshop_beneficiary_records', ['upload_run_id'], unique=False)
    op.create_table('workshop_beneficiary_sources_config',
    sa.Column('source_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('bundesland', sa.String(length=80), nullable=True),
    sa.Column('fonds', sa.String(length=40), nullable=True),
    sa.Column('periode', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_landing_page', sa.String(length=500), nullable=True),
    sa.Column('update_frequency_days', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('sheet_name', sa.String(length=80), nullable=True),
    sa.Column('header_row', sa.Integer(), server_default='0', nullable=True),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('last_successful_harvest_at', sa.DateTime(), nullable=True),
    sa.Column('last_harvest_run_id', sa.String(length=36), nullable=True),
    sa.Column('last_seen_sha256', sa.String(length=64), nullable=True),
    sa.Column('record_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('quality', sa.String(length=8), nullable=True),
    sa.Column('coverage_note', sa.Text(), nullable=True),
    sa.Column('notes_for_pruefer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('source_key')
    )
    op.create_index(op.f('ix_workshop_beneficiary_sources_config_country_code'), 'workshop_beneficiary_sources_config', ['country_code'], unique=False)
    op.create_table('workshop_company_entities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('canonical_name_normalized', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('ultimate_parent_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('first_match_method', sa.String(length=40), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['workshop_company_entities.id'], ),
    sa.ForeignKeyConstraint(['ultimate_parent_entity_id'], ['workshop_company_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lei')
    )
    op.create_index('ix_company_entity_name_norm', 'workshop_company_entities', ['canonical_name_normalized'], unique=False)
    op.create_index(op.f('ix_workshop_company_entities_canonical_name'), 'workshop_company_entities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_workshop_company_entities_canonical_name_normalized'), 'workshop_company_entities', ['canonical_name_normalized'], unique=False)
    op.create_index(op.f('ix_workshop_company_entities_country_code'), 'workshop_company_entities', ['country_code'], unique=False)
    op.create_index(op.f('ix_workshop_company_entities_parent_entity_id'), 'workshop_company_entities', ['parent_entity_id'], unique=False)
    op.create_table('workshop_corporate_lookup_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_normalized', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corp_cache_query_fetched', 'workshop_corporate_lookup_cache', ['query_normalized', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_workshop_corporate_lookup_cache_expires_at'), 'workshop_corporate_lookup_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_workshop_corporate_lookup_cache_fetched_at'), 'workshop_corporate_lookup_cache', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_workshop_corporate_lookup_cache_query_normalized'), 'workshop_corporate_lookup_cache', ['query_normalized'], unique=False)
    op.create_table('workshop_doc_download_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_doc_download_log_downloaded_at'), 'workshop_doc_download_log', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_workshop_doc_download_log_file_id'), 'workshop_doc_download_log', ['file_id'], unique=False)
    op.create_table('workshop_doc_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('visibility', sa.String(length=20), server_default='members_read', nullable=False),
    sa.Column('upload_policy', sa.String(length=20), server_default='moderators', nullable=False),
    sa.Column('is_shared_pool', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_doc_folders_parent_id'), 'workshop_doc_folders', ['parent_id'], unique=False)
    op.create_table('workshop_email_templates',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('workshop_entity_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_module', sa.String(length=20), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('text_input', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_module', 'source_record_id', name='uq_entity_embedding_source')
    )
    op.create_index(op.f('ix_workshop_entity_embeddings_source_module'), 'workshop_entity_embeddings', ['source_module'], unique=False)
    op.create_index(op.f('ix_workshop_entity_embeddings_source_record_id'), 'workshop_entity_embeddings', ['source_record_id'], unique=False)
    op.create_table('workshop_entity_match_llm_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('total_eligible', sa.Integer(), nullable=True),
    sa.Column('total_verified', sa.Integer(), nullable=True),
    sa.Column('matches_confirmed', sa.Integer(), nullable=True),
    sa.Column('matches_rejected', sa.Integer(), nullable=True),
    sa.Column('matches_unknown', sa.Integer(), nullable=True),
    sa.Column('skipped_due_to_timeout', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_entity_match_llm_runs_started_at'), 'workshop_entity_match_llm_runs', ['started_at'], unique=False)
    op.create_table('workshop_forum_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_forum_categories_slug'), 'workshop_forum_categories', ['slug'], unique=True)
    op.create_table('workshop_forum_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_forum_tags_slug'), 'workshop_forum_tags', ['slug'], unique=True)
    op.create_table('workshop_harvest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('sources_total', sa.Integer(), server_default='0', nullable=True),
    sa.Column('sources_ok', sa.Integer(), server_default='0', nullable=True),
    sa.Column('sources_skipped', sa.Integer(), server_default='0', nullable=True),
    sa.Column('sources_failed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('log_excerpt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_harvest_runs_started_at'), 'workshop_harvest_runs', ['started_at'], unique=False)
    op.create_table('workshop_harvest_source_updates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('bundesland', sa.String(length=64), nullable=True),
    sa.Column('fonds', sa.String(length=40), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_before', sa.Integer(), nullable=True),
    sa.Column('rows_after', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256_old', sa.String(length=64), nullable=True),
    sa.Column('sha256_new', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_harvest_source_updates_run_id'), 'workshop_harvest_source_updates', ['run_id'], unique=False)
    op.create_index(op.f('ix_workshop_harvest_source_updates_source'), 'workshop_harvest_source_updates', ['source'], unique=False)
    op.create_table('workshop_icebreaker_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_llm_call_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('backend', sa.String(length=20), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_call_model_time', 'workshop_llm_call_log', ['model', 'created_at'], unique=False)
    op.create_index('ix_llm_call_route_time', 'workshop_llm_call_log', ['route', 'created_at'], unique=False)
    op.create_index('ix_llm_call_status_time', 'workshop_llm_call_log', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_workshop_llm_call_log_created_at'), 'workshop_llm_call_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_workshop_llm_call_log_model'), 'workshop_llm_call_log', ['model'], unique=False)
    op.create_index(op.f('ix_workshop_llm_call_log_route'), 'workshop_llm_call_log', ['route'], unique=False)
    op.create_index(op.f('ix_workshop_llm_call_log_status'), 'workshop_llm_call_log', ['status'], unique=False)
    op.create_table('workshop_llm_question_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('scenario', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_normalized', sa.String(length=500), nullable=True),
    sa.Column('documents_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('with_context', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('answer_path', sa.String(length=64), nullable=True),
    sa.Column('matched_mode', sa.String(length=40), nullable=True),
    sa.Column('name_filter_label', sa.String(length=120), nullable=True),
    sa.Column('items_returned', sa.Integer(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('tok_per_s', sa.Float(), nullable=True),
    sa.Column('ttfb_ms', sa.Integer(), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=True),
    sa.Column('response_total_chars', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_feedback', sa.String(length=20), nullable=True),
    sa.Column('user_feedback_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_log_scenario_created', 'workshop_llm_question_log', ['scenario', 'created_at'], unique=False)
    op.create_index(op.f('ix_workshop_llm_question_log_answer_path'), 'workshop_llm_question_log', ['answer_path'], unique=False)
    op.create_index(op.f('ix_workshop_llm_question_log_created_at'), 'workshop_llm_question_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_workshop_llm_question_log_prompt_normalized'), 'workshop_llm_question_log', ['prompt_normalized'], unique=False)
    op.create_index(op.f('ix_workshop_llm_question_log_scenario'), 'workshop_llm_question_log', ['scenario'], unique=False)
    op.create_index(op.f('ix_workshop_llm_question_log_user_id'), 'workshop_llm_question_log', ['user_id'], unique=False)
    op.create_table('workshop_meta',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('location_short', sa.String(length=255), nullable=True),
    sa.Column('location_full', sa.String(length=500), nullable=True),
    sa.Column('organizer', sa.String(length=255), nullable=True),
    sa.Column('registration_deadline', sa.String(length=50), nullable=True),
    sa.Column('qr_url', sa.String(length=500), nullable=True),
    sa.Column('admin_pin', sa.String(length=20), nullable=True),
    sa.Column('workshop_mode', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('phase', sa.String(length=8), server_default='live', nullable=False),
    sa.Column('archive_started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_user_unread', 'workshop_notifications', ['user_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_workshop_notifications_created_at'), 'workshop_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_workshop_notifications_user_id'), 'workshop_notifications', ['user_id'], unique=False)
    op.create_table('workshop_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aktenzeichen', sa.String(length=100), nullable=False),
    sa.Column('geschaeftsjahr', sa.String(length=10), nullable=False),
    sa.Column('program', sa.String(length=255), nullable=True),
    sa.Column('foerderphase', sa.Enum('FP_2014_2020', 'FP_2021_2027', name='foerderphase'), nullable=True),
    sa.Column('zuwendungsempfaenger', sa.String(length=255), nullable=True),
    sa.Column('projekttitel', sa.String(length=500), nullable=True),
    sa.Column('foerderkennzeichen', sa.String(length=100), nullable=True),
    sa.Column('bewilligungszeitraum', sa.String(length=100), nullable=True),
    sa.Column('gesamtkosten', sa.String(length=50), nullable=True),
    sa.Column('foerdersumme', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_projects_aktenzeichen'), 'workshop_projects', ['aktenzeichen'], unique=False)
    op.create_table('workshop_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('fund', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('qr_login_secret', sa.String(length=128), nullable=True),
    sa.Column('qr_secret_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('privacy_accepted', sa.Boolean(), nullable=True),
    sa.Column('ai_confirmation_consent', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='attendee', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('bundesland', sa.String(length=64), nullable=True),
    sa.Column('function_role', sa.String(length=80), nullable=True),
    sa.Column('signup_reason', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.Column('quota_bytes', sa.BigInteger(), server_default=sa.text('209715200'), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_workshop_registrations_role'), 'workshop_registrations', ['role'], unique=False)
    op.create_index(op.f('ix_workshop_registrations_status'), 'workshop_registrations', ['status'], unique=False)
    op.create_table('workshop_sanctions_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_key', sa.String(length=40), nullable=False),
    sa.Column('entry_id', sa.String(length=120), nullable=False),
    sa.Column('schema', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_normalized', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('birth_date', sa.Text(), nullable=True),
    sa.Column('countries', sa.Text(), nullable=True),
    sa.Column('addresses', sa.Text(), nullable=True),
    sa.Column('identifiers', sa.Text(), nullable=True),
    sa.Column('sanctions_program', sa.Text(), nullable=True),
    sa.Column('program_ids', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refresh_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'entry_id', name='uq_sanctions_source_entry')
    )
    op.create_index('ix_sanctions_schema_source', 'workshop_sanctions_entries', ['source_key', 'schema'], unique=False)
    op.create_index('ix_sanctions_search', 'workshop_sanctions_entries', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_workshop_sanctions_entries_entry_id'), 'workshop_sanctions_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_workshop_sanctions_entries_name'), 'workshop_sanctions_entries', ['name'], unique=False)
    op.create_index(op.f('ix_workshop_sanctions_entries_name_normalized'), 'workshop_sanctions_entries', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_workshop_sanctions_entries_refresh_run_id'), 'workshop_sanctions_entries', ['refresh_run_id'], unique=False)
    op.create_index(op.f('ix_workshop_sanctions_entries_schema'), 'workshop_sanctions_entries', ['schema'], unique=False)
    op.create_index(op.f('ix_workshop_sanctions_entries_source_key'), 'workshop_sanctions_entries', ['source_key'], unique=False)
    op.create_table('workshop_sanctions_refresh',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256_old', sa.String(length=64), nullable=True),
    sa.Column('sha256_new', sa.String(length=64), nullable=True),
    sa.Column('rows_before', sa.Integer(), nullable=True),
    sa.Column('rows_after', sa.Integer(), nullable=True),
    sa.Column('persons_before', sa.Integer(), nullable=True),
    sa.Column('persons_after', sa.Integer(), nullable=True),
    sa.Column('organizations_before', sa.Integer(), nullable=True),
    sa.Column('organizations_after', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sources', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_sanctions_refresh_started_at'), 'workshop_sanctions_refresh', ['started_at'], unique=False)
    op.create_table('workshop_security_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_security_audit_action'), 'workshop_security_audit', ['action'], unique=False)
    op.create_index(op.f('ix_workshop_security_audit_actor_user_id'), 'workshop_security_audit', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_workshop_security_audit_created_at'), 'workshop_security_audit', ['created_at'], unique=False)
    op.create_table('workshop_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_workshop_sessions_user_id'), 'workshop_sessions', ['user_id'], unique=False)
    op.create_table('workshop_state_aid_awards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=60), nullable=False),
    sa.Column('source_record_id', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('harvest_run_id', sa.String(length=36), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=500), nullable=False),
    sa.Column('beneficiary_name_normalized', sa.String(length=500), nullable=False),
    sa.Column('beneficiary_identifier', sa.String(length=200), nullable=True),
    sa.Column('beneficiary_type', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('country_name', sa.String(length=80), nullable=True),
    sa.Column('nuts_code', sa.String(length=20), nullable=True),
    sa.Column('nuts_label', sa.String(length=160), nullable=True),
    sa.Column('nuts_level', sa.Integer(), nullable=True),
    sa.Column('nace_code', sa.String(length=10), nullable=True),
    sa.Column('nace_label', sa.String(length=240), nullable=True),
    sa.Column('aid_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('aid_currency', sa.String(length=8), nullable=True),
    sa.Column('aid_amount_eur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('aid_nominal_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('aid_instrument', sa.String(length=240), nullable=True),
    sa.Column('aid_objective', sa.Text(), nullable=True),
    sa.Column('aid_measure_title', sa.Text(), nullable=True),
    sa.Column('granting_authority', sa.String(length=300), nullable=True),
    sa.Column('entrusted_entity', sa.String(length=300), nullable=True),
    sa.Column('financial_intermediaries', sa.String(length=300), nullable=True),
    sa.Column('granting_date', sa.Date(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('measure_reference', sa.String(length=60), nullable=True),
    sa.Column('sa_reference', sa.String(length=40), nullable=True),
    sa.Column('case_url', sa.String(length=500), nullable=True),
    sa.Column('decision_url', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'source_record_id', name='uq_state_aid_source_record')
    )
    op.create_index('ix_state_aid_country_date', 'workshop_state_aid_awards', ['country_code', 'granting_date'], unique=False)
    op.create_index('ix_state_aid_country_nuts', 'workshop_state_aid_awards', ['country_code', 'nuts_code'], unique=False)
    op.create_index('ix_state_aid_nuts_prefix', 'workshop_state_aid_awards', ['nuts_code'], unique=False)
    op.create_index('ix_state_aid_search', 'workshop_state_aid_awards', ['beneficiary_name_normalized', 'country_code'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_aid_amount_eur'), 'workshop_state_aid_awards', ['aid_amount_eur'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_beneficiary_identifier'), 'workshop_state_aid_awards', ['beneficiary_identifier'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_beneficiary_name_normalized'), 'workshop_state_aid_awards', ['beneficiary_name_normalized'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_country_code'), 'workshop_state_aid_awards', ['country_code'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_granting_date'), 'workshop_state_aid_awards', ['granting_date'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_harvest_run_id'), 'workshop_state_aid_awards', ['harvest_run_id'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_nuts_code'), 'workshop_state_aid_awards', ['nuts_code'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_sa_reference'), 'workshop_state_aid_awards', ['sa_reference'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_source_key'), 'workshop_state_aid_awards', ['source_key'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_awards_source_record_id'), 'workshop_state_aid_awards', ['source_record_id'], unique=False)
    op.create_table('workshop_state_aid_harvest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('records_seen', sa.Integer(), server_default='0', nullable=True),
    sa.Column('records_inserted', sa.Integer(), server_default='0', nullable=True),
    sa.Column('records_updated', sa.Integer(), server_default='0', nullable=True),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('records_skipped', sa.Integer(), server_default='0', nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=80), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=True),
    sa.Column('source_last_modified', sa.DateTime(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_state_aid_harvest_runs_source_key'), 'workshop_state_aid_harvest_runs', ['source_key'], unique=False)
    op.create_index(op.f('ix_workshop_state_aid_harvest_runs_started_at'), 'workshop_state_aid_harvest_runs', ['started_at'], unique=False)
    op.create_table('workshop_state_aid_sources',
    sa.Column('source_key', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('last_successful_harvest_at', sa.DateTime(), nullable=True),
    sa.Column('last_record_date', sa.Date(), nullable=True),
    sa.Column('record_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('coverage_note', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=8), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('expected_total', sa.Integer(), nullable=True),
    sa.Column('expected_total_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('source_key')
    )
    op.create_index(op.f('ix_workshop_state_aid_sources_country_code'), 'workshop_state_aid_sources', ['country_code'], unique=False)
    op.create_table('workshop_topic_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('registration_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'MODERATION', name='submissionvisibility'), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_validation_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('module', sa.String(length=40), server_default='state_aid', nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checks_total', sa.Integer(), nullable=True),
    sa.Column('checks_passed', sa.Integer(), nullable=True),
    sa.Column('checks_warned', sa.Integer(), nullable=True),
    sa.Column('checks_failed', sa.Integer(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_module_started', 'workshop_validation_runs', ['module', 'started_at'], unique=False)
    op.create_index(op.f('ix_workshop_validation_runs_started_at'), 'workshop_validation_runs', ['started_at'], unique=False)
    op.create_table('workshop_agenda_forum_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agenda_item_id', sa.String(length=36), nullable=False),
    sa.Column('author_registration_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_organization', sa.String(length=255), nullable=True),
    sa.Column('author_role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['workshop_agenda_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_registration_id'], ['workshop_registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_agenda_forum_posts_agenda_item_id'), 'workshop_agenda_forum_posts', ['agenda_item_id'], unique=False)
    op.create_index(op.f('ix_workshop_agenda_forum_posts_author_registration_id'), 'workshop_agenda_forum_posts', ['author_registration_id'], unique=False)
    op.create_table('workshop_checklists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['workshop_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_checklists_project_id'), 'workshop_checklists', ['project_id'], unique=False)
    op.create_table('workshop_doc_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('current_version_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('storage_dir', sa.String(length=255), nullable=False),
    sa.Column('uploader_id', sa.String(length=36), nullable=True),
    sa.Column('uploader_name', sa.String(length=160), nullable=True),
    sa.Column('uploader_organization', sa.String(length=255), nullable=True),
    sa.Column('uploader_bundesland', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('download_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['workshop_doc_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_doc_files_folder_id'), 'workshop_doc_files', ['folder_id'], unique=False)
    op.create_index(op.f('ix_workshop_doc_files_uploaded_at'), 'workshop_doc_files', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_workshop_doc_files_uploader_bundesland'), 'workshop_doc_files', ['uploader_bundesland'], unique=False)
    op.create_index(op.f('ix_workshop_doc_files_uploader_id'), 'workshop_doc_files', ['uploader_id'], unique=False)
    op.create_table('workshop_entity_matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('source_module', sa.String(length=20), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('source_table', sa.String(length=40), nullable=False),
    sa.Column('match_method', sa.String(length=40), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('rejected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['workshop_company_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_module', 'source_record_id', name='uq_entity_match_source')
    )
    op.create_index('ix_entity_match_module_table', 'workshop_entity_matches', ['source_module', 'source_table'], unique=False)
    op.create_index(op.f('ix_workshop_entity_matches_entity_id'), 'workshop_entity_matches', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workshop_entity_matches_source_module'), 'workshop_entity_matches', ['source_module'], unique=False)
    op.create_index(op.f('ix_workshop_entity_matches_source_record_id'), 'workshop_entity_matches', ['source_record_id'], unique=False)
    op.create_table('workshop_forum_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_md', sa.Text(), server_default='', nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=160), nullable=True),
    sa.Column('author_organization', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_post_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('solved_post_id', sa.String(length=36), nullable=True),
    sa.Column('agenda_item_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['workshop_forum_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forum_threads_category_lastpost', 'workshop_forum_threads', ['category_id', 'last_post_at'], unique=False)
    op.create_index(op.f('ix_workshop_forum_threads_agenda_item_id'), 'workshop_forum_threads', ['agenda_item_id'], unique=False)
    op.create_index(op.f('ix_workshop_forum_threads_author_user_id'), 'workshop_forum_threads', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_workshop_forum_threads_category_id'), 'workshop_forum_threads', ['category_id'], unique=False)
    op.create_index(op.f('ix_workshop_forum_threads_created_at'), 'workshop_forum_threads', ['created_at'], unique=False)
    op.create_index(op.f('ix_workshop_forum_threads_last_post_at'), 'workshop_forum_threads', ['last_post_at'], unique=False)
    op.create_table('workshop_password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=20), server_default='reset', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['workshop_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_password_reset_tokens_token_hash'), 'workshop_password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_workshop_password_reset_tokens_user_id'), 'workshop_password_reset_tokens', ['user_id'], unique=False)
    op.create_table('workshop_project_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_label', sa.String(length=100), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('parse_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['workshop_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_project_documents_project_id'), 'workshop_project_documents', ['project_id'], unique=False)
    op.create_table('workshop_doc_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('uploader_id', sa.String(length=36), nullable=True),
    sa.Column('uploader_name', sa.String(length=160), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['workshop_doc_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_version_file_no', 'workshop_doc_versions', ['file_id', 'version_no'], unique=False)
    op.create_index(op.f('ix_workshop_doc_versions_file_id'), 'workshop_doc_versions', ['file_id'], unique=False)
    op.create_table('workshop_forum_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('parent_post_id', sa.String(length=36), nullable=True),
    sa.Column('author_user_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=160), nullable=True),
    sa.Column('author_organization', sa.String(length=255), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('edit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['workshop_forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_forum_posts_author_user_id'), 'workshop_forum_posts', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_workshop_forum_posts_created_at'), 'workshop_forum_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_workshop_forum_posts_thread_id'), 'workshop_forum_posts', ['thread_id'], unique=False)
    op.create_table('workshop_forum_read_state',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('last_read_post_id', sa.String(length=36), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['workshop_forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'thread_id')
    )
    op.create_table('workshop_forum_thread_tags',
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['workshop_forum_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['workshop_forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'tag_id')
    )
    op.create_table('workshop_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checklist_id', sa.String(length=36), nullable=False),
    sa.Column('question_key', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_type', sa.Enum('BOOLEAN', 'BOOLEAN_JN', 'DATE', 'AMOUNT', 'ENUM', 'TEXT', name='answertype'), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('answer_value', sa.Text(), nullable=True),
    sa.Column('remark_manual', sa.Text(), nullable=True),
    sa.Column('remark_ai', sa.Text(), nullable=True),
    sa.Column('remark_ai_edited', sa.Text(), nullable=True),
    sa.Column('remark_ai_status', sa.Enum('DRAFT', 'ACCEPTED', 'EDITED', 'REJECTED', name='remarkaistatus'), nullable=True),
    sa.Column('reject_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['workshop_checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'question_key', name='uq_checklist_question_key')
    )
    op.create_index(op.f('ix_workshop_questions_checklist_id'), 'workshop_questions', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_workshop_questions_question_key'), 'workshop_questions', ['question_key'], unique=False)
    op.create_table('workshop_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['workshop_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_evidence_question_id'), 'workshop_evidence', ['question_id'], unique=False)
    op.create_table('workshop_forum_reactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['workshop_forum_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', 'kind', name='uq_reaction_post_user_kind')
    )
    op.create_index(op.f('ix_workshop_forum_reactions_post_id'), 'workshop_forum_reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_workshop_forum_reactions_user_id'), 'workshop_forum_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workshop_forum_reactions_user_id'), table_name='workshop_forum_reactions')
    op.drop_index(op.f('ix_workshop_forum_reactions_post_id'), table_name='workshop_forum_reactions')
    op.drop_table('workshop_forum_reactions')
    op.drop_index(op.f('ix_workshop_evidence_question_id'), table_name='workshop_evidence')
    op.drop_table('workshop_evidence')
    op.drop_index(op.f('ix_workshop_questions_question_key'), table_name='workshop_questions')
    op.drop_index(op.f('ix_workshop_questions_checklist_id'), table_name='workshop_questions')
    op.drop_table('workshop_questions')
    op.drop_table('workshop_forum_thread_tags')
    op.drop_table('workshop_forum_read_state')
    op.drop_index(op.f('ix_workshop_forum_posts_thread_id'), table_name='workshop_forum_posts')
    op.drop_index(op.f('ix_workshop_forum_posts_created_at'), table_name='workshop_forum_posts')
    op.drop_index(op.f('ix_workshop_forum_posts_author_user_id'), table_name='workshop_forum_posts')
    op.drop_table('workshop_forum_posts')
    op.drop_index(op.f('ix_workshop_doc_versions_file_id'), table_name='workshop_doc_versions')
    op.drop_index('ix_doc_version_file_no', table_name='workshop_doc_versions')
    op.drop_table('workshop_doc_versions')
    op.drop_index(op.f('ix_workshop_project_documents_project_id'), table_name='workshop_project_documents')
    op.drop_table('workshop_project_documents')
    op.drop_index(op.f('ix_workshop_password_reset_tokens_user_id'), table_name='workshop_password_reset_tokens')
    op.drop_index(op.f('ix_workshop_password_reset_tokens_token_hash'), table_name='workshop_password_reset_tokens')
    op.drop_table('workshop_password_reset_tokens')
    op.drop_index(op.f('ix_workshop_forum_threads_last_post_at'), table_name='workshop_forum_threads')
    op.drop_index(op.f('ix_workshop_forum_threads_created_at'), table_name='workshop_forum_threads')
    op.drop_index(op.f('ix_workshop_forum_threads_category_id'), table_name='workshop_forum_threads')
    op.drop_index(op.f('ix_workshop_forum_threads_author_user_id'), table_name='workshop_forum_threads')
    op.drop_index(op.f('ix_workshop_forum_threads_agenda_item_id'), table_name='workshop_forum_threads')
    op.drop_index('ix_forum_threads_category_lastpost', table_name='workshop_forum_threads')
    op.drop_table('workshop_forum_threads')
    op.drop_index(op.f('ix_workshop_entity_matches_source_record_id'), table_name='workshop_entity_matches')
    op.drop_index(op.f('ix_workshop_entity_matches_source_module'), table_name='workshop_entity_matches')
    op.drop_index(op.f('ix_workshop_entity_matches_entity_id'), table_name='workshop_entity_matches')
    op.drop_index('ix_entity_match_module_table', table_name='workshop_entity_matches')
    op.drop_table('workshop_entity_matches')
    op.drop_index(op.f('ix_workshop_doc_files_uploader_id'), table_name='workshop_doc_files')
    op.drop_index(op.f('ix_workshop_doc_files_uploader_bundesland'), table_name='workshop_doc_files')
    op.drop_index(op.f('ix_workshop_doc_files_uploaded_at'), table_name='workshop_doc_files')
    op.drop_index(op.f('ix_workshop_doc_files_folder_id'), table_name='workshop_doc_files')
    op.drop_table('workshop_doc_files')
    op.drop_index(op.f('ix_workshop_checklists_project_id'), table_name='workshop_checklists')
    op.drop_table('workshop_checklists')
    op.drop_index(op.f('ix_workshop_agenda_forum_posts_author_registration_id'), table_name='workshop_agenda_forum_posts')
    op.drop_index(op.f('ix_workshop_agenda_forum_posts_agenda_item_id'), table_name='workshop_agenda_forum_posts')
    op.drop_table('workshop_agenda_forum_posts')
    op.drop_index(op.f('ix_workshop_validation_runs_started_at'), table_name='workshop_validation_runs')
    op.drop_index('ix_validation_module_started', table_name='workshop_validation_runs')
    op.drop_table('workshop_validation_runs')
    op.drop_table('workshop_topic_submissions')
    op.drop_index(op.f('ix_workshop_state_aid_sources_country_code'), table_name='workshop_state_aid_sources')
    op.drop_table('workshop_state_aid_sources')
    op.drop_index(op.f('ix_workshop_state_aid_harvest_runs_started_at'), table_name='workshop_state_aid_harvest_runs')
    op.drop_index(op.f('ix_workshop_state_aid_harvest_runs_source_key'), table_name='workshop_state_aid_harvest_runs')
    op.drop_table('workshop_state_aid_harvest_runs')
    op.drop_index(op.f('ix_workshop_state_aid_awards_source_record_id'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_source_key'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_sa_reference'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_nuts_code'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_harvest_run_id'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_granting_date'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_country_code'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_beneficiary_name_normalized'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_beneficiary_identifier'), table_name='workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_state_aid_awards_aid_amount_eur'), table_name='workshop_state_aid_awards')
    op.drop_index('ix_state_aid_search', table_name='workshop_state_aid_awards')
    op.drop_index('ix_state_aid_nuts_prefix', table_name='workshop_state_aid_awards')
    op.drop_index('ix_state_aid_country_nuts', table_name='workshop_state_aid_awards')
    op.drop_index('ix_state_aid_country_date', table_name='workshop_state_aid_awards')
    op.drop_table('workshop_state_aid_awards')
    op.drop_index(op.f('ix_workshop_sessions_user_id'), table_name='workshop_sessions')
    op.drop_table('workshop_sessions')
    op.drop_index(op.f('ix_workshop_security_audit_created_at'), table_name='workshop_security_audit')
    op.drop_index(op.f('ix_workshop_security_audit_actor_user_id'), table_name='workshop_security_audit')
    op.drop_index(op.f('ix_workshop_security_audit_action'), table_name='workshop_security_audit')
    op.drop_table('workshop_security_audit')
    op.drop_index(op.f('ix_workshop_sanctions_refresh_started_at'), table_name='workshop_sanctions_refresh')
    op.drop_table('workshop_sanctions_refresh')
    op.drop_index(op.f('ix_workshop_sanctions_entries_source_key'), table_name='workshop_sanctions_entries')
    op.drop_index(op.f('ix_workshop_sanctions_entries_schema'), table_name='workshop_sanctions_entries')
    op.drop_index(op.f('ix_workshop_sanctions_entries_refresh_run_id'), table_name='workshop_sanctions_entries')
    op.drop_index(op.f('ix_workshop_sanctions_entries_name_normalized'), table_name='workshop_sanctions_entries')
    op.drop_index(op.f('ix_workshop_sanctions_entries_name'), table_name='workshop_sanctions_entries')
    op.drop_index(op.f('ix_workshop_sanctions_entries_entry_id'), table_name='workshop_sanctions_entries')
    op.drop_index('ix_sanctions_search', table_name='workshop_sanctions_entries')
    op.drop_index('ix_sanctions_schema_source', table_name='workshop_sanctions_entries')
    op.drop_table('workshop_sanctions_entries')
    op.drop_index(op.f('ix_workshop_registrations_status'), table_name='workshop_registrations')
    op.drop_index(op.f('ix_workshop_registrations_role'), table_name='workshop_registrations')
    op.drop_table('workshop_registrations')
    op.drop_index(op.f('ix_workshop_projects_aktenzeichen'), table_name='workshop_projects')
    op.drop_table('workshop_projects')
    op.drop_index(op.f('ix_workshop_notifications_user_id'), table_name='workshop_notifications')
    op.drop_index(op.f('ix_workshop_notifications_created_at'), table_name='workshop_notifications')
    op.drop_index('ix_notif_user_unread', table_name='workshop_notifications')
    op.drop_table('workshop_notifications')
    op.drop_table('workshop_meta')
    op.drop_index(op.f('ix_workshop_llm_question_log_user_id'), table_name='workshop_llm_question_log')
    op.drop_index(op.f('ix_workshop_llm_question_log_scenario'), table_name='workshop_llm_question_log')
    op.drop_index(op.f('ix_workshop_llm_question_log_prompt_normalized'), table_name='workshop_llm_question_log')
    op.drop_index(op.f('ix_workshop_llm_question_log_created_at'), table_name='workshop_llm_question_log')
    op.drop_index(op.f('ix_workshop_llm_question_log_answer_path'), table_name='workshop_llm_question_log')
    op.drop_index('ix_llm_log_scenario_created', table_name='workshop_llm_question_log')
    op.drop_table('workshop_llm_question_log')
    op.drop_index(op.f('ix_workshop_llm_call_log_status'), table_name='workshop_llm_call_log')
    op.drop_index(op.f('ix_workshop_llm_call_log_route'), table_name='workshop_llm_call_log')
    op.drop_index(op.f('ix_workshop_llm_call_log_model'), table_name='workshop_llm_call_log')
    op.drop_index(op.f('ix_workshop_llm_call_log_created_at'), table_name='workshop_llm_call_log')
    op.drop_index('ix_llm_call_status_time', table_name='workshop_llm_call_log')
    op.drop_index('ix_llm_call_route_time', table_name='workshop_llm_call_log')
    op.drop_index('ix_llm_call_model_time', table_name='workshop_llm_call_log')
    op.drop_table('workshop_llm_call_log')
    op.drop_table('workshop_icebreaker_questions')
    op.drop_index(op.f('ix_workshop_harvest_source_updates_source'), table_name='workshop_harvest_source_updates')
    op.drop_index(op.f('ix_workshop_harvest_source_updates_run_id'), table_name='workshop_harvest_source_updates')
    op.drop_table('workshop_harvest_source_updates')
    op.drop_index(op.f('ix_workshop_harvest_runs_started_at'), table_name='workshop_harvest_runs')
    op.drop_table('workshop_harvest_runs')
    op.drop_index(op.f('ix_workshop_forum_tags_slug'), table_name='workshop_forum_tags')
    op.drop_table('workshop_forum_tags')
    op.drop_index(op.f('ix_workshop_forum_categories_slug'), table_name='workshop_forum_categories')
    op.drop_table('workshop_forum_categories')
    op.drop_index(op.f('ix_workshop_entity_match_llm_runs_started_at'), table_name='workshop_entity_match_llm_runs')
    op.drop_table('workshop_entity_match_llm_runs')
    op.drop_index(op.f('ix_workshop_entity_embeddings_source_record_id'), table_name='workshop_entity_embeddings')
    op.drop_index(op.f('ix_workshop_entity_embeddings_source_module'), table_name='workshop_entity_embeddings')
    op.drop_table('workshop_entity_embeddings')
    op.drop_table('workshop_email_templates')
    op.drop_index(op.f('ix_workshop_doc_folders_parent_id'), table_name='workshop_doc_folders')
    op.drop_table('workshop_doc_folders')
    op.drop_index(op.f('ix_workshop_doc_download_log_file_id'), table_name='workshop_doc_download_log')
    op.drop_index(op.f('ix_workshop_doc_download_log_downloaded_at'), table_name='workshop_doc_download_log')
    op.drop_table('workshop_doc_download_log')
    op.drop_index(op.f('ix_workshop_corporate_lookup_cache_query_normalized'), table_name='workshop_corporate_lookup_cache')
    op.drop_index(op.f('ix_workshop_corporate_lookup_cache_fetched_at'), table_name='workshop_corporate_lookup_cache')
    op.drop_index(op.f('ix_workshop_corporate_lookup_cache_expires_at'), table_name='workshop_corporate_lookup_cache')
    op.drop_index('ix_corp_cache_query_fetched', table_name='workshop_corporate_lookup_cache')
    op.drop_table('workshop_corporate_lookup_cache')
    op.drop_index(op.f('ix_workshop_company_entities_parent_entity_id'), table_name='workshop_company_entities')
    op.drop_index(op.f('ix_workshop_company_entities_country_code'), table_name='workshop_company_entities')
    op.drop_index(op.f('ix_workshop_company_entities_canonical_name_normalized'), table_name='workshop_company_entities')
    op.drop_index(op.f('ix_workshop_company_entities_canonical_name'), table_name='workshop_company_entities')
    op.drop_index('ix_company_entity_name_norm', table_name='workshop_company_entities')
    op.drop_table('workshop_company_entities')
    op.drop_index(op.f('ix_workshop_beneficiary_sources_config_country_code'), table_name='workshop_beneficiary_sources_config')
    op.drop_table('workshop_beneficiary_sources_config')
    op.drop_index(op.f('ix_workshop_beneficiary_records_upload_run_id'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_source_record_id'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_source_key'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_nuts_code'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_funded_at'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_fonds'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_country_code'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_cost_total'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_bundesland'), table_name='workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_records_beneficiary_name_normalized'), table_name='workshop_beneficiary_records')
    op.drop_index('ix_beneficiary_search', table_name='workshop_beneficiary_records')
    op.drop_index('ix_beneficiary_country_bundesland', table_name='workshop_beneficiary_records')
    op.drop_table('workshop_beneficiary_records')
    op.drop_index(op.f('ix_workshop_beneficiary_harvest_runs_started_at'), table_name='workshop_beneficiary_harvest_runs')
    op.drop_index(op.f('ix_workshop_beneficiary_harvest_runs_source_key'), table_name='workshop_beneficiary_harvest_runs')
    op.drop_table('workshop_beneficiary_harvest_runs')
    op.drop_index(op.f('ix_workshop_audit_report_log_query'), table_name='workshop_audit_report_log')
    op.drop_index(op.f('ix_workshop_audit_report_log_pruefer_user_id'), table_name='workshop_audit_report_log')
    op.drop_index(op.f('ix_workshop_audit_report_log_created_at'), table_name='workshop_audit_report_log')
    op.drop_index('ix_audit_report_query_created', table_name='workshop_audit_report_log')
    op.drop_table('workshop_audit_report_log')
    op.drop_table('workshop_audit_log')
    op.drop_table('workshop_agenda_items')
    op.drop_index(op.f('ix_workshop_access_log_user_id'), table_name='workshop_access_log')
    op.drop_index(op.f('ix_workshop_access_log_status_code'), table_name='workshop_access_log')
    op.drop_index(op.f('ix_workshop_access_log_path_template'), table_name='workshop_access_log')
    op.drop_index(op.f('ix_workshop_access_log_path'), table_name='workshop_access_log')
    op.drop_index(op.f('ix_workshop_access_log_llm_model'), table_name='workshop_access_log')
    op.drop_index(op.f('ix_workshop_access_log_created_at'), table_name='workshop_access_log')
    op.drop_index('ix_access_log_user_time', table_name='workshop_access_log')
    op.drop_index('ix_access_log_path_time', table_name='workshop_access_log')
    op.drop_index('ix_access_log_model_time', table_name='workshop_access_log')
    op.drop_table('workshop_access_log')
    # ### end Alembic commands ###
