"""0002 checklist template subsystem

Revision ID: f14eb310648f
Revises: 27eba23abfeb
Create Date: 2026-05-24 09:02:40.706578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f14eb310648f'
down_revision: Union[str, None] = '27eba23abfeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_checklist_node_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('node_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('node_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('old_parent_id', sa.String(length=36), nullable=True),
    sa.Column('new_parent_id', sa.String(length=36), nullable=True),
    sa.Column('old_position', sa.Integer(), nullable=True),
    sa.Column('new_position', sa.Integer(), nullable=True),
    sa.Column('changed_by_id', sa.String(length=36), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['workshop_registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cl_history_template_created', 'workshop_checklist_node_history', ['template_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_node_history_change_type'), 'workshop_checklist_node_history', ['change_type'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_node_history_changed_by_id'), 'workshop_checklist_node_history', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_node_history_created_at'), 'workshop_checklist_node_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_node_history_node_id'), 'workshop_checklist_node_history', ['node_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_node_history_template_id'), 'workshop_checklist_node_history', ['template_id'], unique=False)
    op.create_table('workshop_checklist_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_language', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('target_language', sa.String(length=8), server_default='de', nullable=False),
    sa.Column('source_document_name', sa.String(length=255), nullable=True),
    sa.Column('source_document_path', sa.String(length=500), nullable=True),
    sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('statistics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['workshop_registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_checklist_templates_owner_id'), 'workshop_checklist_templates', ['owner_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_templates_status'), 'workshop_checklist_templates', ['status'], unique=False)
    op.create_table('workshop_checklist_answer_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workshop_checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_checklist_answer_sets_template_id'), 'workshop_checklist_answer_sets', ['template_id'], unique=False)
    op.create_table('workshop_checklist_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workshop_checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_checklist_categories_template_id'), 'workshop_checklist_categories', ['template_id'], unique=False)
    op.create_table('workshop_checklist_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('invited_user_id', sa.String(length=36), nullable=False),
    sa.Column('invited_by_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='viewer', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_user_id'], ['workshop_registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workshop_checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_checklist_invites_invited_user_id'), 'workshop_checklist_invites', ['invited_user_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_invites_status'), 'workshop_checklist_invites', ['status'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_invites_template_id'), 'workshop_checklist_invites', ['template_id'], unique=False)
    op.create_table('workshop_checklist_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='viewer', nullable=False),
    sa.Column('invited_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workshop_checklist_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['workshop_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'user_id', name='uq_cl_member')
    )
    op.create_index(op.f('ix_workshop_checklist_members_template_id'), 'workshop_checklist_members', ['template_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_members_user_id'), 'workshop_checklist_members', ['user_id'], unique=False)
    op.create_table('workshop_checklist_answer_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('answer_set_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_standard', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_entfaellt', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['answer_set_id'], ['workshop_checklist_answer_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_checklist_answer_options_answer_set_id'), 'workshop_checklist_answer_options', ['answer_set_id'], unique=False)
    op.create_table('workshop_checklist_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('node_type', sa.String(length=16), server_default='QUESTION', nullable=False),
    sa.Column('branch', sa.String(length=8), nullable=True),
    sa.Column('ja_label', sa.Text(), nullable=True),
    sa.Column('nein_label', sa.Text(), nullable=True),
    sa.Column('decision_parent_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('public_remark', sa.Text(), nullable=True),
    sa.Column('remark_snippets_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eingabetyp', sa.Integer(), nullable=True),
    sa.Column('answer_type', sa.String(length=16), nullable=True),
    sa.Column('answer_set_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('legal_reference', sa.Text(), nullable=True),
    sa.Column('relevant_documents_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_header_field', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_text_en', sa.Text(), nullable=True),
    sa.Column('translated_text_de', sa.Text(), nullable=True),
    sa.Column('review_text_de', sa.Text(), nullable=True),
    sa.Column('translation_status', sa.String(length=16), nullable=True),
    sa.Column('translation_error', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('translated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['answer_set_id'], ['workshop_checklist_answer_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['workshop_checklist_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['workshop_checklist_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workshop_checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cl_nodes_template_sort', 'workshop_checklist_nodes', ['template_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_nodes_answer_set_id'), 'workshop_checklist_nodes', ['answer_set_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_nodes_category_id'), 'workshop_checklist_nodes', ['category_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_nodes_decision_parent_id'), 'workshop_checklist_nodes', ['decision_parent_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_nodes_parent_id'), 'workshop_checklist_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_nodes_template_id'), 'workshop_checklist_nodes', ['template_id'], unique=False)
    op.create_table('workshop_checklist_node_locks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('locked_by_id', sa.String(length=36), nullable=False),
    sa.Column('locked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['locked_by_id'], ['workshop_registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['workshop_checklist_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', name='uq_cl_node_lock')
    )
    op.create_index(op.f('ix_workshop_checklist_node_locks_expires_at'), 'workshop_checklist_node_locks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_node_locks_locked_by_id'), 'workshop_checklist_node_locks', ['locked_by_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_node_locks_node_id'), 'workshop_checklist_node_locks', ['node_id'], unique=False)
    op.create_index(op.f('ix_workshop_checklist_node_locks_template_id'), 'workshop_checklist_node_locks', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workshop_checklist_node_locks_template_id'), table_name='workshop_checklist_node_locks')
    op.drop_index(op.f('ix_workshop_checklist_node_locks_node_id'), table_name='workshop_checklist_node_locks')
    op.drop_index(op.f('ix_workshop_checklist_node_locks_locked_by_id'), table_name='workshop_checklist_node_locks')
    op.drop_index(op.f('ix_workshop_checklist_node_locks_expires_at'), table_name='workshop_checklist_node_locks')
    op.drop_table('workshop_checklist_node_locks')
    op.drop_index(op.f('ix_workshop_checklist_nodes_template_id'), table_name='workshop_checklist_nodes')
    op.drop_index(op.f('ix_workshop_checklist_nodes_parent_id'), table_name='workshop_checklist_nodes')
    op.drop_index(op.f('ix_workshop_checklist_nodes_decision_parent_id'), table_name='workshop_checklist_nodes')
    op.drop_index(op.f('ix_workshop_checklist_nodes_category_id'), table_name='workshop_checklist_nodes')
    op.drop_index(op.f('ix_workshop_checklist_nodes_answer_set_id'), table_name='workshop_checklist_nodes')
    op.drop_index('ix_cl_nodes_template_sort', table_name='workshop_checklist_nodes')
    op.drop_table('workshop_checklist_nodes')
    op.drop_index(op.f('ix_workshop_checklist_answer_options_answer_set_id'), table_name='workshop_checklist_answer_options')
    op.drop_table('workshop_checklist_answer_options')
    op.drop_index(op.f('ix_workshop_checklist_members_user_id'), table_name='workshop_checklist_members')
    op.drop_index(op.f('ix_workshop_checklist_members_template_id'), table_name='workshop_checklist_members')
    op.drop_table('workshop_checklist_members')
    op.drop_index(op.f('ix_workshop_checklist_invites_template_id'), table_name='workshop_checklist_invites')
    op.drop_index(op.f('ix_workshop_checklist_invites_status'), table_name='workshop_checklist_invites')
    op.drop_index(op.f('ix_workshop_checklist_invites_invited_user_id'), table_name='workshop_checklist_invites')
    op.drop_table('workshop_checklist_invites')
    op.drop_index(op.f('ix_workshop_checklist_categories_template_id'), table_name='workshop_checklist_categories')
    op.drop_table('workshop_checklist_categories')
    op.drop_index(op.f('ix_workshop_checklist_answer_sets_template_id'), table_name='workshop_checklist_answer_sets')
    op.drop_table('workshop_checklist_answer_sets')
    op.drop_index(op.f('ix_workshop_checklist_templates_status'), table_name='workshop_checklist_templates')
    op.drop_index(op.f('ix_workshop_checklist_templates_owner_id'), table_name='workshop_checklist_templates')
    op.drop_table('workshop_checklist_templates')
    op.drop_index(op.f('ix_workshop_checklist_node_history_template_id'), table_name='workshop_checklist_node_history')
    op.drop_index(op.f('ix_workshop_checklist_node_history_node_id'), table_name='workshop_checklist_node_history')
    op.drop_index(op.f('ix_workshop_checklist_node_history_created_at'), table_name='workshop_checklist_node_history')
    op.drop_index(op.f('ix_workshop_checklist_node_history_changed_by_id'), table_name='workshop_checklist_node_history')
    op.drop_index(op.f('ix_workshop_checklist_node_history_change_type'), table_name='workshop_checklist_node_history')
    op.drop_index('ix_cl_history_template_created', table_name='workshop_checklist_node_history')
    op.drop_table('workshop_checklist_node_history')
    # ### end Alembic commands ###
